# Generated by Django 4.0.1 on 2022-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('riddle', models.CharField(max_length=10000)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
    ]
