# Generated by Django 4.0.1 on 2022-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_history_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='riddle',
        ),
        migrations.AddField(
            model_name='riddle',
            name='correct_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riddle',
            name='hint_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='ques_solved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
