# Generated by Django 4.0.1 on 2022-01-22 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_riddle_hint_hintdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hintdata',
            unique_together={('user', 'ques')},
        ),
    ]
